### ISSUE TITLE
Authorization doesn’t work with uppercase letters of email

### ISSUE THREAD

**Issue by anatoli** [DmitryPosadskiy/SkillRepeatFront#11]
When I registred, I put email in lowercase. Now, when I try to auth and use my email with first Uppercase letter, auth doesn’t work with error “User does not exist. Please, check your request”. Auth with all lowercase letters work.

**Comment by anatoli** [comment]
v0.2.2, Chrome

**Comment by DmitryPosadskiy** [comment]
@anatoli Anatoli, hi!

Thank you for your report!

It's a bug and it has fixed in version 0.2.3.
It should be working now.
