### ISSUE TITLE
После регистрации открывается пустой экран скиллов. 

### ISSUE THREAD

**Issue by AlinaGimp** [DmitryPosadskiy/SkillRepeatFront#8]
При входе главный экран выглядит пусто и создается впечатление, что страница не загрузилась полностью.
![photo_2019-08-26_16-49-04](https://user-images.githubusercontent.com/54886600/64255164-7da3b400-cf29-11e9-9ba7-d6167b0bcc02.jpg)

**Comment by DmitryPosadskiy** [comment]
@AlinaGimp Alina, здравствуйте!

Спасибо за ваш репорт.
Будет исправлено в ближайшей версии.

**Comment by DmitryPosadskiy** [comment]
@AlinaGimp Алина, здравствуйте!

Исправлено в v0.2.2
