### ISSUE TITLE
Ошибка при создании скилла.

### ISSUE THREAD

**Issue by AlinaGimp** [DmitryPosadskiy/SkillRepeatFront#9]
При попытке сохранить скилл, возникает ошибка.
![photo_2019-08-26_17-36-29](https://user-images.githubusercontent.com/54886600/64255355-decb8780-cf29-11e9-9f40-b1713f7da5a1.jpg)

**Comment by DmitryPosadskiy** [comment]
@AlinaGimp Алина, здравствуйте!

Большое спасибо за очередной репорт!

Для диагностирования ошибки мне необходимы дополнительные данные:
Насколько давно возникла проблема?
Какая версия приложения использовалась? (Версию приложения можно посмотреть на вкладке Account, она имеет вид "v0.2.0")

**Comment by AlinaGimp** [comment]
Версия была v0.2.0

**Comment by DmitryPosadskiy** [comment]
@AlinaGimp Алина, спасибо за ответ!

Проверье, пожалуйста, сейчас.
Проблема должна быть исправлена, начиная с версии 0.2.1.

**Comment by AlinaGimp** [comment]
Спасибо, все работает!
